# Variables (replace with your own values)
@base_url = http://localhost:8000
@username = testuser
@password = mBqU EeIw 2aY6 Nxtm sTWu kOSc
# @password = Bpab m4US BD1A 5QmT E1NX rFPO
# @password = F623 uYkb EXEI SBXl rNd1 6OMU
@admin_username = admin
@admin_password = ufEK id77 GTpK fGdZ G1Zq 42E8

# @base_url = http://localhost:8881
# @username = testuser
# @password = tljJ S27Y x1lD s65F w49d 7iQR
# @admin_username = admin
# @admin_password = QeX4 LrOs 50wB qjZD 1AyX tEwa

###

# Get me; pika profile
GET {{base_url}}/wp-json/pika/v1/auth/me
Authorization: Basic {{admin_username}}:{{admin_password}}

###

# Get settings
GET {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}

###

# Update settings - valid USD currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "INR"
}

###

# Update settings - valid gemini api key
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{admin_username}}:{{admin_password}}
Content-Type: application/json

{
  "gemini_api_key": "AIzaSyD-sample-api-key"
}

###

# Update settings - invalid currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "XYZ"
}

###

# Update settings - valid EUR currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "EUR"
}

###

# Update settings - invalid key
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "invalid_key": "value"
}

###

# Get all tags
GET {{base_url}}/wp-json/pika/v1/tags
Authorization: Basic {{username}}:{{password}}

###

# Add a new tag
POST {{base_url}}/wp-json/pika/v1/tags
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Tag 2",
  "color": "#000000",
  "bgColor": "#ffffff",
  "icon": "tag",
  "description": "Test description"
}

###

# Get a tag by id
GET {{base_url}}/wp-json/pika/v1/tags/6
Authorization: Basic {{username}}:{{password}}

###

# Update a tag
PUT {{base_url}}/wp-json/pika/v1/tags/6
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Tag 2 Updated 1",
  "color": "#000000",
  "bgColor": "#ffffff"
}

###

# Delete a tag
DELETE {{base_url}}/wp-json/pika/v1/tags/7
Authorization: Basic {{username}}:{{password}}

###

# Get all categories
GET {{base_url}}/wp-json/pika/v1/categories
Authorization: Basic {{username}}:{{password}}

###

# Add a new category
POST {{base_url}}/wp-json/pika/v1/categories
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test child Category 12",
  "icon": "tag",
  "color": "#000000",
  "bgColor": "#ffffff",
  "type": "expense",
  "description": "Test child category description",
  "parentId": 61
}

###

# Get a category by id
GET {{base_url}}/wp-json/pika/v1/categories/1
Authorization: Basic {{username}}:{{password}}

###

# Update a category
PUT {{base_url}}/wp-json/pika/v1/categories/65
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Category 12 Updated 1",
  "icon": "tag"
}

###

# Delete a category
DELETE {{base_url}}/wp-json/pika/v1/categories/61
Authorization: Basic {{username}}:{{password}}

###

# Upload a file - account avatar
POST {{base_url}}/wp-json/pika/v1/upload/avatar
Authorization: Basic {{username}}:{{password}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="entityType"

person
------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="avatar01.png"
Content-Type: image/png

< docs/images/avatar01.png
------WebKitFormBoundary--

###

# Upload a file - transaction attachment - image
POST {{base_url}}/wp-json/pika/v1/upload/attachment
Authorization: Basic {{username}}:{{password}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="entityType"

transaction
------WebKitFormBoundary
Content-Disposition: form-data; name="attachmentType"

image
------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="image01.png"
Content-Type: image/png

< docs/images/avatar01.png
------WebKitFormBoundary--

###

# Upload a file - transaction attachment - pdf
POST {{base_url}}/wp-json/pika/v1/upload/attachment
Authorization: Basic {{username}}:{{password}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="entityType"

transaction
------WebKitFormBoundary
Content-Disposition: form-data; name="attachmentType"

document
------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="document01.pdf"
Content-Type: application/pdf

< /Users/mohammed.ashad/Downloads/EAadhaar_2003702210041020250609180022_1806202514229.pdf
------WebKitFormBoundary--

###

# Get all people
GET {{base_url}}/wp-json/pika/v1/people
Authorization: Basic {{admin_username}}:{{admin_password}}

###

# Create a new person
POST {{base_url}}/wp-json/pika/v1/people
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Person 1",
  "email": "testperson1@example.com",
  "phone": "1234567890",
  "avatarId": "17"
}

###

# Get a person
GET {{base_url}}/wp-json/pika/v1/people/1
Authorization: Basic {{admin_username}}:{{admin_password}}

###

# Update a person
PUT {{base_url}}/wp-json/pika/v1/people/1
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Person 1 Updated 1",
  "email": "testperson1@example.com"
}

###

# Delete a person
DELETE {{base_url}}/wp-json/pika/v1/people/7
Authorization: Basic {{username}}:{{password}}

###

# Get all accounts
GET {{base_url}}/wp-json/pika/v1/accounts
Authorization: Basic {{username}}:{{password}}

###

# Create a new account
POST {{base_url}}/wp-json/pika/v1/accounts
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Account 1",
  "description": "Test account description",
  "avatarId": 10
}

###

# Create a new account
POST {{base_url}}/wp-json/pika/v1/accounts
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Account",
  "description": "Test account description",
  "bgColor": "#000000",
  "color": "#ffffff",
  "icon": "wallet"
}

###

# Get an account
GET {{base_url}}/wp-json/pika/v1/accounts/1
Authorization: Basic {{username}}:{{password}}

###

# Update an account
PUT {{base_url}}/wp-json/pika/v1/accounts/3
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "name": "Test Account 3 Updated 1",
  "description": "Test account description updated",
  "icon": "wallet",
  "avatarId": 14
}

###

# Delete an account
DELETE {{base_url}}/wp-json/pika/v1/accounts/2
Authorization: Basic {{username}}:{{password}}

###

# Get all transactions
GET {{base_url}}/wp-json/pika/v1/transactions
Authorization: Basic {{username}}:{{password}}

###

# Create a new transaction
POST {{base_url}}/wp-json/pika/v1/transactions
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Test Transaction 1",
  "amount": 101,
  "date": "2025-01-01",
  "type": "income",
  "categoryId": 50,
  "accountId": 1,
  "personId": 3,
  "tags": [2],
  "attachments": [23]
}

###

# Get a transaction
GET {{base_url}}/wp-json/pika/v1/transactions/3
Authorization: Basic {{username}}:{{password}}

###

# Update a transaction
PUT {{base_url}}/wp-json/pika/v1/transactions/3
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Test Transaction 1 Updated 1",
  "amount": 102,
  "date": "2025-01-01",
  "note": "Test transaction note updated",
  "attachments": [13],
  "tags": [1, 3]
}

###

# Delete a transaction
DELETE {{base_url}}/wp-json/pika/v1/transactions/4
Authorization: Basic {{username}}:{{password}}

###

# Get weekly expenses
GET {{base_url}}/wp-json/pika/v1/analytics/weekly-expenses
Authorization: Basic {{username}}:{{password}}

###

# Get daily expenses
GET {{base_url}}/wp-json/pika/v1/analytics/daily-expenses
Authorization: Basic {{admin_username}}:{{admin_password}}
Content-Type: application/json

{
  "month": 7,
  "year": 2025
}

###

# Get monthly summary
GET {{base_url}}/wp-json/pika/v1/analytics/monthly-summary
Authorization: Basic {{admin_username}}:{{admin_password}}
Content-Type: application/json

{
  "month": 7,
  "year": 2025
}

###

# Test gemini response
GET {{base_url}}/wp-json/pika/v1/ai/test
Authorization: Basic {{admin_username}}:{{admin_password}}

###