# Variables (replace with your own values)
@base_url = http://localhost:8000
@username = testuser
@password = mBqU EeIw 2aY6 Nxtm sTWu kOSc
@admin_username = admin
@admin_password = ufEK id77 GTpK fGdZ G1Zq 42E8

# @base_url = http://localhost:8881
# @username = testuser
# @password = tljJ S27Y x1lD s65F w49d 7iQR
# @admin_username = admin
# @admin_password = QeX4 LrOs 50wB qjZD 1AyX tEwa

###

# get me; pika profile
GET {{base_url}}/wp-json/pika/v1/auth/me
Authorization: Basic {{username}}:{{password}}

###

# get settings
GET {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}

###

# update settings - valid USD currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "INR"
}

###

# update settings - invalid currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "XYZ"
}

###

# update settings - valid EUR currency
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "currency": "EUR"
}

###

# update settings - invalid key
PUT {{base_url}}/wp-json/pika/v1/settings
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "invalid_key": "value"
}

###

# get users
GET {{base_url}}/wp-json/wp/v2/users/me
Authorization: Basic {{username}}:{{password}}

###

# get pages
GET {{base_url}}/wp-json/wp/v2/pages
Authorization: Basic {{username}}:{{password}}